version: '3'

services:
  product-service:
    container_name: product-service
    build: ./product
    volumes:
      - ./product:/app
    ports:
      - 5001:8080

  website:
    container_name: website
    build: ./website
    volumes:
      - ./website:/app
    ports:
      - 5000:3000
    depends_on:
      - product-service
